name: Build & Cache Flake Outputs

on:
  workflow_dispatch:
  push:

jobs:
  build-and-cache:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            system: aarch64-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Lix
        uses: canidae-solutions/lix-quick-install-action@v3

      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: https://cache.xenia.dog
          token: ${{ secrets.ATTIC_TOKEN }}
          cache: prod

      - name: Install nix-fast-build
        run: nix profile install "github:Mic92/nix-fast-build"

      - name: Run checks
        run: nix-fast-build --no-nom --no-link --skip-cached --option accept-flake-config true
