name: Build & Release ISO Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 1,15 * *"
  push:
    paths:
      - "modules/iso/**"

jobs:
  build-isos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install Lix
        uses: canidae-solutions/lix-quick-install-action@v3

      # WATCH: https://git.lix.systems/lix-project/lix/issues/545
      - name: Loosen Apparmor Restrictions
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Setup Attic Cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: https://cache.xenia.dog
          token: ${{ secrets.ATTIC_TOKEN }}
          cache: prod

      - name: Build Iso
        run: nix build -L .#nixosConfigurations.blume.config.system.build.isoImage

      - name: Upload Release Artifacts
        run: |
          rev=$(nix eval --raw .#nixosConfigurations.blume.config.system.configurationRevision)
          release=$(date +"%Y-%m-%d")
          gh release create "$release-$rev"
          gh release upload "$release-$rev" ./result/iso/*.iso
        env:
          GH_TOKEN: ${{ github.token }}
