name: Bump Flake Inputs

on:
  workflow_dispatch:
  schedule:
    - cron: "4 0 * * *"

jobs:
  update-lockfile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux

    outputs:
      pr: ${{ steps.pr.outputs.pull-request-url }}
      branch: ${{ steps.pr.outputs.pull-request-branch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install Lix
        uses: canidae-solutions/lix-quick-install-action@v3

      - name: Update Lockfile
        id: pr
        uses: DeterminateSystems/update-flake-lock@v27
        with:
          token: ${{ secrets.FLAKE_UPDATE_PAT }}
          commit-msg: "flake.lock: update all inputs"
          pr-title: "flake.lock: update all inputs"
          branch: update-flake-inputs
          pr-body: |
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```

  check:
    name: Check Flake
    needs: update-lockfile

    uses: ./.github/workflows/build-and-cache.yml
    with:
      ref: ${{ needs.update-lockfile.outputs.branch }}

  merge:
    name: Merge Pull Request
    needs: [update-lockfile, check]

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Merge Pull Request
        run: gh pr merge --rebase --auto --delete-branch "$PR"
        env:
          GH_TOKEN: ${{ github.token }}
          PR: ${{ needs.update-lockfile.outputs.pr }}
